########## RoboticStaff configuration ##########
# Plugin made by RaynLegends
# Bukkitdev page: http://dev.bukkit.org/bukkit-plugins/roboticstaff/
# Github: https://github.com/RaynLegends/RoboticStaff/
### If you find a bug, please let me know :D ###

config-version: '2.0' # Don't edit this!
update-checker: 'true' # Change to "false" if you don't want to check updates

roboticstaff-prefix: '&6[RoboticStaff]&e '

## Helpme ##

helpme-help: 'Need help? Type "/helpme [id]"!'

helpme-ask:
  - 'What is that plugin?'
  - 'Can I translate the plugin?'
  - 'What are the future features?'

helpme-answer:
  - 'Is a simple plugin which will be able in the future to replace partly your staff'
  - 'Yes, you can! ALL the messages is configurable in config.yml!'
  - 'Check the TODO list of BukkitDev page for a list of the future feature!'

helpme-error-1: 'Invalid ask id!'
helpme-error-2: 'Id must be a number!'
helpme-error-3: 'Right use: "/helpme id"'

## AutoAnswer ##

autoanswer-tag:
  - 'RoboticStaff'
  - 'I, need, help'
  - 'Can, I, become, an, admin %or% I, would, like, to, become, admin'
  - 'Ban, me, please'
  - 'Hi raynlegends %or% Hey raynlegends %or% Good morning raynlegends'
  - 'How, can, I, configure, this, plugin'
  
autoanswer-tag-answer:
  - 'Its the name of this plugin, %player%'
  - 'Type /helpme!'
  - 'Sorry, you cant'
  - '/kick %player%'
  - '%noprefix% &4[Founder] &4Rayn&8Legends&r: Hi %player%'
  - 'Visit the BukkitDev page! &4http://dev.bukkit.org/bukkit-mods/RoboticStaff'

## AntiSwearing ##

antiswearing-words:
  - 'Fuck'
  - 'Shit'
  - 'Bitch'
  
antiswearing-beep: '[BIP]'

## BlockedCommands ##

blockedcommands-message: '&4This command is blocked in this world'

blockedcommands-general:
  - q
  - logout
  - plugins

blockedcommands-perworld:
  world:
    - pl
  world_nether:
    - pl
  world_the_end:
    - pl
    
## AntiSpam ##

antispam-message: 'Wait %time% seconds to send another message'

antispam-delay: '3' # The amount in seconds of the time that players have to wait for send messages
