name: RoboticStaff
main: com.gmail.raynlegends.RoboticStaff.Main
version: 2.0
description: Auto anwser to player message and more!
author: RaynLegends
    
commands:
    helpme:
        description: Type /helpme if you need help!
        usage: /helpme <id>
        permission: roboticstaff.helpme
        permission-message: You don't have permission for do that
    roboticstaff:
        description: General command of RoboticStaff
        usage: /roboticstaff [reload|tag|words|blocked]
        permission: roboticstaff.access
        permission-message: You don't have permission for do that
      
permissions:
    roboticstaff.*:
        description: Gives access to all RoboticStaff commands
        children:
            roboticstaff.helpme: true
            roboticstaff.reload: true
            roboticstaff.autoanswer.list: true
            roboticstaff.autoanswer.bypass: true
            roboticstaff.antiswearing.list: true
            roboticstaff.antiswearing.bypass: true
            roboticstaff.blockedcommands.list: true
            roboticstaff.blockedcommands.bypass: true
            roboticstaff.antispam.bypass: true
    roboticstaff.helpme:
        description: Allows using helpme command
        default: true
    roboticstaff.access:
        description: Access to /roboticstaff
        default: op
    roboticstaff.reload:
        description: Allows to use /roboticstaff reload
        default: op
    roboticstaff.autoanswer.list:
        description: Get a list of tags
        default: op
        children:
            roboticstaff.access: true
    roboticstaff.autoanswer.bypass:
        description: Bypass tags
        default: op
    roboticstaff.antiswearing.list:
        description: Get a list of banned words
        default: op
        children:
            roboticstaff.access: true
    roboticstaff.antiswearing.bypass:
        description: Bypass banned words
        default: op
    roboticstaff.blockedcommands.list:
        description: Get a list of blocked commands
        default: op
        children:
            roboticstaff.access: true
    roboticstaff.blockedcommands.bypass:
        description: Bypass blocked commands
        default: op
    roboticstaff.antispam.bypass:
        description: Bypass all antispam stuffs
        children:
            roboticstaff.antispam.bypass.delay: true
            roboticstaff.antispam.bypass.ipspam: true
            roboticstaff.antispam.bypass.websitespam: true
    roboticstaff.antispam.bypass.delay:
        description: Bypass delay
        default: op
    roboticstaff.antispam.bypass.ipspam:
        description: Bypass ipspam
        default: op
    roboticstaff.antispam.bypass.websitespam:
        description: Bypass websitespam
        default: op